version: "3.8"

services:
  deepseek-vl2:
    image: deepseek-vl2
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
